sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php: 7.0

env:
  global:
    - CODE_COVERAGE=false

  matrix:
    - MAGENTO_VERSION=2.1.0
    - MAGENTO_VERSION=2.1.1
    - MAGENTO_VERSION=2.1.2
    - MAGENTO_VERSION=2.1.3
    # - MAGENTO_VERSION=2.1.4 # Skipping 2.1.4 as 2.1.5 = 2.1.4 + copyright updates
    - MAGENTO_VERSION=2.1.5
    - MAGENTO_VERSION=2.1.6
    - MAGENTO_VERSION=2.1.7
    - MAGENTO_VERSION=2.1.8
    - MAGENTO_VERSION=2.1.9
    - MAGENTO_VERSION=2.2.0

matrix:
  include:
    env: MAGENTO_VERSION=2.2.0 php=7.1 CODE_COVERAGE=true

before_script:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - bash Test/Script/ManageDependencies.sh
  - bash Test/Script/Setup.sh

script:
  - grunt
  - if [ "$CODE_COVERAGE" = "false" ]; then php /tmp/magento2/bin/magento setup:di:compile; fi # Check for compilation errors

after_success:
  - bash Test/Script/AfterSuccess.sh

cache:
  directories:
  - node_modules
  - $HOME/.download_cache
  - $HOME/.composer
  - $HOME/.cache/composer
