sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php:
  - 7.0
#  - 7.1
#  - nightly

env:
  - MAGENTO_VERSION=2.0.8
  - MAGENTO_VERSION=2.0.9
  - MAGENTO_VERSION=2.0.10
  - MAGENTO_VERSION=2.1.0
  - MAGENTO_VERSION=2.1.1
  - MAGENTO_VERSION=2.1.2

before_script:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - phpenv config-rm xdebug.ini
  - composer install
  - bash Test/Setup.sh
  - npm install grunt-cli -g
  - npm install

script:
  - if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - grunt test

cache:
  directories:
  - $HOME/.composer