sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

language: php

php: 7.0

env:
  global:
    - CODE_COVERAGE=false

  matrix:
#    - MAGENTO_VERSION=2.0.8
#    - MAGENTO_VERSION=2.0.9
#    - MAGENTO_VERSION=2.0.10
#    - MAGENTO_VERSION=2.1.0
#    - MAGENTO_VERSION=2.1.1
    - MAGENTO_VERSION=2.1.2
#    - MAGENTO_VERSION=2.1.3

matrix:
  include:
    env: MAGENTO_VERSION=2.1.3 CODE_COVERAGE=true

before_script:
  - export PATH=$PATH:$HOME/.composer/vendor/bin
  - composer config -a -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD
  - bash Test/Script/ManageDependencies.sh
  - bash Test/Script/Setup.sh

script:
  - grunt test

after_success:
  - bash Test/Script/AfterSuccess.sh

cache:
  directories:
  - node_modules
  - $HOME/.download_cache
  - $HOME/.composer
  - $HOME/.cache/composer
